spring:
  datasource:
    url: "jdbc:mysql://localhost/library"
    username: "root"
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

cloud:
  aws:
    s3:
      bucket: valuewith
    stack.auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

